name: Trigger auto deployment for container-app-pwmtsjf2qadu4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-pwmtsjf2qadu4-AutoDeployTrigger-6eebcf33-4a2f-4b10-b527-91c069e307b3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPWMTSJF2QADU4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPWMTSJF2QADU4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPWMTSJF2QADU4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: defaultacrcontainerregistry9d69.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPPWMTSJF2QADU4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPWMTSJF2QADU4_REGISTRY_PASSWORD }}
          containerAppName: container-app-pwmtsjf2qadu4
          resourceGroup: djangoappspaces865192a4
          imageToBuild: defaultacrcontainerregistry9d69.azurecr.io/container-app-pwmtsjf2qadu4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


